In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully")

Libraries imported successfully

In [3]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles/folders here:")
print(os.listdir())

Current folder:
C:\Users\lakshay shrivastav\OneDrive\Desktop\Marketing-Attribution-CAC-Analysis

Files/folders here:
['.gitignore', '.ipynb_checkpoints', '01_Data_Understanding.ipynb', 'dashboard', 'data', 'docs', 'models', 'notebooks', 'outputs', 'README.md', 'requirements.txt', 'sql', 'src', 'venv']

In [4]:
touchpoints = pd.read_csv("data/raw/touchpoints.csv")
users = pd.read_csv("data/raw/users_summary.csv")

print("Touchpoints shape:", touchpoints.shape)
print("Users shape:", users.shape)

Touchpoints shape: (47584, 8)
Users shape: (20000, 4)

In [5]:
print("Touchpoints columns:")
print(touchpoints.columns.tolist())

print("\nUsers columns:")
print(users.columns.tolist())

Touchpoints columns:
['user_id', 'touch_order', 'journey_length', 'channel', 'timestamp', 'cost', 'converted', 'revenue']

Users columns:
['user_id', 'journey_length', 'converted', 'revenue']

In [6]:
touchpoints.head()

,user_id,touch_order,journey_length,channel,timestamp,cost,converted,revenue
0,U000000,1,1,Referral,2025-02-05 00:00:00,0.00,0,0.0
1,U000001,1,1,Paid Social,2025-03-05 00:00:00,13.06,0,0.0
2,U000002,1,1,Direct,2025-03-01 00:00:00,0.00,0,0.0
3,U000003,1,2,Direct,2025-01-19 00:00:00,0.00,0,0.0
4,U000003,2,2,Referral,2025-01-19 09:41:53,0.00,0,0.0

In [7]:
users.head()

   user_id  journey_length  converted  revenue
0  U000000               1          0      0.0
1  U000001               1          0      0.0
2  U000002               1          0      0.0
3  U000003               2          0      0.0
4  U000004               2          0      0.0

In [8]:
touchpoints.info()

<class 'pandas.DataFrame'>
RangeIndex: 47584 entries, 0 to 47583
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   user_id         47584 non-null  str
 1   touch_order     47584 non-null  int64
 2   journey_length  47584 non-null  int64
 3   channel         47584 non-null  str
 4   timestamp       47584 non-null  str
 5   cost            47584 non-null  float64
 6   converted       47584 non-null  int64
 7   revenue         47584 non-null  float64
dtypes: float64(2), int64(3), str(3)
memory usage: 2.9 MB

In [9]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   user_id         20000 non-null  str
 1   journey_length  20000 non-null  int64
 2   converted       20000 non-null  int64
 3   revenue         20000 non-null  float64
dtypes: float64(1), int64(2), str(1)
memory usage: 625.1 KB

In [10]:
print("Missing values in touchpoints:")
print(touchpoints.isnull().sum())

print("\nMissing values in users:")
print(users.isnull().sum())

Missing values in touchpoints:
user_id           0
touch_order       0
journey_length    0
channel           0
timestamp         0
cost              0
converted         0
revenue           0
dtype: int64

Missing values in users:
user_id           0
journey_length    0
converted         0
revenue           0
dtype: int64

In [11]:
print("Duplicate rows in touchpoints:", touchpoints.duplicated().sum())
print("Duplicate rows in users:", users.duplicated().sum())

Duplicate rows in touchpoints: 0
Duplicate rows in users: 0

In [12]:
print("Marketing channels:")
print(touchpoints["channel"].unique())

print("\nNumber of channels:", touchpoints["channel"].nunique())

Marketing channels:
<StringArray>
[      'Referral',    'Paid Social',         'Direct',    'Paid Search',
 'Organic Search',          'Email',        'Display']
Length: 7, dtype: str

Number of channels: 7

In [13]:
print("Touchpoint conversion values:")
print(touchpoints["converted"].value_counts())

print("\nUser conversion values:")
print(users["converted"].value_counts())

Touchpoint conversion values:
converted
0    37123
1    10461
Name: count, dtype: int64

User conversion values:
converted
0    16486
1     3514
Name: count, dtype: int64

In [14]:
print("Cost statistics:")
print(touchpoints["cost"].describe())

print("\nRevenue statistics:")
print(touchpoints["revenue"].describe())

print("\nJourney length statistics:")
print(touchpoints["journey_length"].describe())

Cost statistics:
count    47584.000000
mean         6.838147
std         12.266817
min          0.000000
25%          0.000000
50%          0.000000
75%          8.220000
max        108.620000
Name: cost, dtype: float64

Revenue statistics:
count    47584.000000
mean       238.619087
std        919.932902
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max      16396.960000
Name: revenue, dtype: float64

Journey length statistics:
count    47584.000000
mean         3.015551
std          1.250925
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max          5.000000
Name: journey_length, dtype: float64

In [15]:
touchpoint_users = set(touchpoints["user_id"])
summary_users = set(users["user_id"])

print("Users in touchpoints:", len(touchpoint_users))
print("Users in summary:", len(summary_users))

print("Users missing from touchpoints:", len(summary_users - touchpoint_users))
print("Users missing from summary:", len(touchpoint_users - summary_users))

Users in touchpoints: 20000
Users in summary: 20000
Users missing from touchpoints: 0
Users missing from summary: 0

In [16]:
actual_journey_length = (
    touchpoints.groupby("user_id")["touch_order"]
    .count()
)

comparison = pd.DataFrame({
    "actual_touchpoints": actual_journey_length,
    "reported_journey_length": users.set_index("user_id")["journey_length"]
})

print("Users where journey length does NOT match:")
print(
    (comparison["actual_touchpoints"] != comparison["reported_journey_length"]).sum()
)

Users where journey length does NOT match:
0

In [17]:
touch_order_check = (
    touchpoints.groupby("user_id")["touch_order"]
    .agg(["min", "max", "count"])
)

invalid_order = touch_order_check[
    (touch_order_check["min"] != 1) |
    (touch_order_check["max"] != touch_order_check["count"])
]

print("Users with invalid touch order:", len(invalid_order))

Users with invalid touch order: 0

In [18]:
conversion_check = (
    touchpoints.groupby("user_id")["converted"]
    .max()
    .rename("touchpoint_converted")
    .to_frame()
    .join(
        users.set_index("user_id")["converted"]
        .rename("summary_converted")
    )
)

print(
    "Users with conversion mismatch:",
    (conversion_check["touchpoint_converted"] != conversion_check["summary_converted"]).sum()
)

Users with conversion mismatch: 0

In [19]:
revenue_check = touchpoints.groupby("user_id").agg(
    converted=("converted", "max"),
    revenue=("revenue", "max")
)

print("Non-converted users with revenue:")
print(
    ((revenue_check["converted"] == 0) & 
     (revenue_check["revenue"] > 0)).sum()
)

print("\nConverted users with zero revenue:")
print(
    ((revenue_check["converted"] == 1) & 
     (revenue_check["revenue"] <= 0)).sum()
)

Non-converted users with revenue:
0

Converted users with zero revenue:
0

In [20]:
channel_cost = (
    touchpoints.groupby("channel")["cost"]
    .agg(["sum", "mean"])
    .sort_values("sum", ascending=False)
)

channel_cost

                      sum       mean
channel
Paid Search     231677.45  30.511978
Paid Social      72535.83  10.206252
Display          21173.13   3.951685
Email                0.00   0.000000
Direct               0.00   0.000000
Organic Search       0.00   0.000000
Referral             0.00   0.000000

In [22]:
total_users = users["user_id"].nunique()
converted_users = users["converted"].sum()
conversion_rate = converted_users / total_users * 100
total_revenue = users["revenue"].sum()
total_spend = touchpoints["cost"].sum()

print("Total Users:", total_users)
print("Converted Users:", converted_users)
print("Conversion Rate:", round(conversion_rate, 2), "%")
print("Total Revenue: ₹", round(total_revenue, 2))
print("Total Marketing Spend: ₹", round(total_spend, 2))

Total Users: 20000
Converted Users: 3514
Conversion Rate: 17.57 %
Total Revenue: ₹ 11354450.64
Total Marketing Spend: ₹ 325386.41

In [23]:
journey_distribution = (
    users["journey_length"]
    .value_counts()
    .sort_index()
)

journey_distribution

journey_length
1    5923
2    6023
3    4011
4    2633
5    1410
Name: count, dtype: int64

In [24]:
journey_conversion = (
    users.groupby("journey_length")
    .agg(
        users=("user_id", "count"),
        conversions=("converted", "sum"),
        revenue=("revenue", "sum")
    )
)

journey_conversion["conversion_rate"] = (
    journey_conversion["conversions"] /
    journey_conversion["users"] * 100
)

journey_conversion

                users  conversions     revenue  conversion_rate
journey_length
1                5923          473  1501145.33         7.985818
2                6023          912  2982249.66        15.141956
3                4011          871  2868650.84        21.715283
4                2633          739  2342071.96        28.066844
5                1410          519  1660332.85        36.808511

In [25]:
channel_touchpoints = (
    touchpoints["channel"]
    .value_counts()
    .rename("touchpoints")
)

channel_touchpoints

channel
Paid Search       7593
Direct            7297
Paid Social       7107
Organic Search    6989
Email             6732
Referral          6508
Display           5358
Name: touchpoints, dtype: int64

In [26]:
channel_conversions = (
    touchpoints[touchpoints["converted"] == 1]
    .groupby("channel")["user_id"]
    .nunique()
    .sort_values(ascending=False)
)

channel_conversions

channel
Paid Social       1500
Direct            1418
Paid Search       1342
Email             1288
Organic Search    1212
Referral          1135
Display           1022
Name: user_id, dtype: int64

Step — Channel Performance Analysis

In [27]:
channel_summary = (
    touchpoints.groupby("channel")
    .agg(
        touchpoints=("user_id", "count"),
        unique_users=("user_id", "nunique"),
        spend=("cost", "sum")
    )
    .sort_values("spend", ascending=False)
)

channel_summary

                touchpoints  unique_users      spend
channel
Paid Search            7593          6664  231677.45
Paid Social            7107          6127   72535.83
Display                5358          4799   21173.13
Email                  6732          5913       0.00
Direct                 7297          6552       0.00
Organic Search         6989          6015       0.00
Referral               6508          5666       0.00

In [28]:
converted_by_channel = (
    touchpoints[touchpoints["converted"] == 1]
    .groupby("channel")["user_id"]
    .nunique()
    .rename("converted_users")
)

channel_summary = channel_summary.join(converted_by_channel)

channel_summary

                touchpoints  unique_users      spend  converted_users
channel
Paid Search            7593          6664  231677.45             1342
Paid Social            7107          6127   72535.83             1500
Display                5358          4799   21173.13             1022
Email                  6732          5913       0.00             1288
Direct                 7297          6552       0.00             1418
Organic Search         6989          6015       0.00             1212
Referral               6508          5666       0.00             1135

In [29]:
channel_summary["observed_conversion_rate"] = (
    channel_summary["converted_users"] /
    channel_summary["unique_users"] * 100
)

channel_summary

,touchpoints,unique_users,spend,converted_users,observed_conversion_rate
channel,,,,,
Paid Search,7593,6664,231677.45,1342,20.138055
Paid Social,7107,6127,72535.83,1500,24.481802
Display,5358,4799,21173.13,1022,21.296103
Email,6732,5913,0.00,1288,21.782513
Direct,7297,6552,0.00,1418,21.642247
Organic Search,6989,6015,0.00,1212,20.149626
Referral,6508,5666,0.00,1135,20.031768

In [30]:
channel_summary.round(2)

,touchpoints,unique_users,spend,converted_users,observed_conversion_rate
channel,,,,,
Paid Search,7593,6664,231677.45,1342,20.14
Paid Social,7107,6127,72535.83,1500,24.48
Display,5358,4799,21173.13,1022,21.30
Email,6732,5913,0.00,1288,21.78
Direct,7297,6552,0.00,1418,21.64
Organic Search,6989,6015,0.00,1212,20.15
Referral,6508,5666,0.00,1135,20.03

Next Step — Build Last-Touch Attribution

In [31]:
last_touch = (
    touchpoints
    .sort_values(["user_id", "touch_order"])
    .groupby("user_id")
    .tail(1)
)

last_touch.head()

,user_id,touch_order,journey_length,channel,timestamp,cost,converted,revenue
0,U000000,1,1,Referral,2025-02-05 00:00:00,0.00,0,0.0
1,U000001,1,1,Paid Social,2025-03-05 00:00:00,13.06,0,0.0
2,U000002,1,1,Direct,2025-03-01 00:00:00,0.00,0,0.0
4,U000003,2,2,Referral,2025-01-19 09:41:53,0.00,0,0.0
6,U000004,2,2,Referral,2025-02-05 06:55:39,0.00,0,0.0

In [32]:
last_touch_converted = last_touch[
    last_touch["converted"] == 1
].copy()

print("Converted customers:", last_touch_converted["user_id"].nunique())

Converted customers: 3514

In [33]:
last_touch_summary = (
    last_touch_converted
    .groupby("channel")
    .agg(
        attributed_conversions=("user_id", "nunique"),
        attributed_revenue=("revenue", "sum")
    )
)

last_touch_summary

                attributed_conversions  attributed_revenue
channel
Direct                            1062          3464899.87
Display                             96           322809.36
Email                              657          2091152.96
Organic Search                     414          1380056.30
Paid Search                        820          2603620.34
Paid Social                        133           451531.91
Referral                           332          1040379.90

In [34]:
last_touch_summary = last_touch_summary.join(
    channel_summary["spend"]
)

last_touch_summary

                attributed_conversions  attributed_revenue      spend
channel
Direct                            1062          3464899.87       0.00
Display                             96           322809.36   21173.13
Email                              657          2091152.96       0.00
Organic Search                     414          1380056.30       0.00
Paid Search                        820          2603620.34  231677.45
Paid Social                        133           451531.91   72535.83
Referral                           332          1040379.90       0.00

In [35]:
last_touch_summary["CAC"] = (
    last_touch_summary["spend"] /
    last_touch_summary["attributed_conversions"]
)

last_touch_summary["ROAS"] = (
    last_touch_summary["attributed_revenue"] /
    last_touch_summary["spend"]
)

last_touch_summary.round(2)

,attributed_conversions,attributed_revenue,spend,CAC,ROAS
channel,,,,,
Direct,1062,3464899.87,0.00,0.00,inf
Display,96,322809.36,21173.13,220.55,15.25
Email,657,2091152.96,0.00,0.00,inf
Organic Search,414,1380056.30,0.00,0.00,inf
Paid Search,820,2603620.34,231677.45,282.53,11.24
Paid Social,133,451531.91,72535.83,545.38,6.22
Referral,332,1040379.90,0.00,0.00,inf

Step 14 — Build Attribution Models

I'll calculate four additional models:

First-Touch
Linear
Time-Decay
Position-Based

In [37]:
first_touch = (
    touchpoints
    .sort_values(["user_id", "touch_order"])
    .groupby("user_id")
    .first()
    .reset_index()
)

first_touch_converted = first_touch[
    first_touch["converted"] == 1
].copy()

print(
    "Converted customers:",
    first_touch_converted["user_id"].nunique()
)

Converted customers: 3514

In [38]:
first_touch_summary = (
    first_touch_converted
    .groupby("channel")
    .agg(
        attributed_conversions=("user_id", "nunique"),
        attributed_revenue=("revenue", "sum")
    )
)

first_touch_summary

                attributed_conversions  attributed_revenue
channel
Direct                             298           514803.97
Display                            703            32053.29
Email                              149           301956.87
Organic Search                     490           165880.69
Paid Search                        324           331792.76
Paid Social                       1095            44715.81
Referral                           455           109941.94

In [39]:
first_touch_summary = first_touch_summary.join(
    channel_summary["spend"]
)

first_touch_summary["CAC"] = (
    first_touch_summary["spend"] /
    first_touch_summary["attributed_conversions"]
)

first_touch_summary["ROAS"] = (
    first_touch_summary["attributed_revenue"] /
    first_touch_summary["spend"]
)

first_touch_summary.round(2)

,attributed_conversions,attributed_revenue,spend,CAC,ROAS
channel,,,,,
Direct,298,514803.97,0.00,0.00,inf
Display,703,32053.29,21173.13,30.12,1.51
Email,149,301956.87,0.00,0.00,inf
Organic Search,490,165880.69,0.00,0.00,inf
Paid Search,324,331792.76,231677.45,715.05,1.43
Paid Social,1095,44715.81,72535.83,66.24,0.62
Referral,455,109941.94,0.00,0.00,inf

In [40]:
# Linear Attribution
# Each touchpoint receives equal credit within the customer journey

converted_touchpoints = touchpoints[
    touchpoints["converted"] == 1
].copy()

converted_touchpoints["linear_credit"] = (
    1 / converted_touchpoints["journey_length"]
)

linear_summary = (
    converted_touchpoints
    .groupby("channel")
    .agg(
        attributed_conversions=("linear_credit", "sum"),
        attributed_revenue=("revenue", "sum")
    )
)

linear_summary

                attributed_conversions  attributed_revenue
channel
Direct                      611.383333          3464899.87
Display                     361.416667           322809.36
Email                       508.300000          2091152.96
Organic Search              479.933333          1380056.30
Paid Search                 565.333333          2603620.34
Paid Social                 561.866667           451531.91
Referral                    425.766667          1040379.90

In [41]:
# Allocate revenue using the same linear attribution credit

converted_touchpoints["linear_attributed_revenue"] = (
    converted_touchpoints["revenue"] *
    converted_touchpoints["linear_credit"]
)

linear_summary = (
    converted_touchpoints
    .groupby("channel")
    .agg(
        attributed_conversions=("linear_credit", "sum"),
        attributed_revenue=("linear_attributed_revenue", "sum")
    )
)

linear_summary = linear_summary.join(
    channel_summary["spend"]
)

linear_summary["CAC"] = (
    linear_summary["spend"] /
    linear_summary["attributed_conversions"]
)

linear_summary["ROAS"] = (
    linear_summary["attributed_revenue"] /
    linear_summary["spend"]
)

linear_summary.round(2)

,attributed_conversions,attributed_revenue,spend,CAC,ROAS
channel,,,,,
Direct,611.38,1515072.11,0.00,0.00,inf
Display,361.42,126726.86,21173.13,58.58,5.99
Email,508.30,900768.26,0.00,0.00,inf
Organic Search,479.93,598467.03,0.00,0.00,inf
Paid Search,565.33,1119978.44,231677.45,409.81,4.83
Paid Social,561.87,185219.78,72535.83,129.10,2.55
Referral,425.77,419839.18,0.00,0.00,inf

In [42]:
# Convert timestamp to datetime

touchpoints["timestamp"] = pd.to_datetime(
    touchpoints["timestamp"]
)

touchpoints[["user_id", "touch_order", "timestamp"]].head()

   user_id  touch_order           timestamp
0  U000000            1 2025-02-05 00:00:00
1  U000001            1 2025-03-05 00:00:00
2  U000002            1 2025-03-01 00:00:00
3  U000003            1 2025-01-19 00:00:00
4  U000003            2 2025-01-19 09:41:53

In [43]:
# Time-Decay Attribution
# More recent touchpoints receive more credit.

converted_touchpoints = touchpoints[
    touchpoints["converted"] == 1
].copy()

# Find the latest touchpoint timestamp for each customer
latest_timestamp = (
    converted_touchpoints
    .groupby("user_id")["timestamp"]
    .transform("max")
)

# Calculate how many days before the final touch each interaction occurred
converted_touchpoints["days_before_conversion"] = (
    latest_timestamp - converted_touchpoints["timestamp"]
).dt.total_seconds() / (60 * 60 * 24)

# Decay factor: credit halves every 7 days
converted_touchpoints["decay_factor"] = (
    0.5 ** (
        converted_touchpoints["days_before_conversion"] / 7
    )
)

# Normalize weights so each customer's total credit = 1
converted_touchpoints["time_decay_credit"] = (
    converted_touchpoints["decay_factor"] /
    converted_touchpoints.groupby("user_id")["decay_factor"].transform("sum")
)

converted_touchpoints[
    [
        "user_id",
        "channel",
        "timestamp",
        "days_before_conversion",
        "time_decay_credit"
    ]
].head(10)

,user_id,channel,timestamp,days_before_conversion,time_decay_credit
42,U000019,Paid Social,2025-03-20 00:00:00,0.173657,0.495701
43,U000019,Paid Search,2025-03-20 04:10:04,0.000000,0.504299
44,U000020,Organic Search,2025-02-24 00:00:00,0.462083,0.488563
45,U000020,Referral,2025-02-24 11:05:24,0.000000,0.511437
50,U000023,Email,2025-02-08 00:00:00,0.000000,1.000000
52,U000025,Direct,2025-03-06 00:00:00,0.000000,1.000000
61,U000029,Display,2025-02-05 00:00:00,3.064618,0.219899
62,U000029,Paid Social,2025-02-05 01:52:03,2.986806,0.221600
63,U000029,Paid Social,2025-02-06 17:11:49,1.348079,0.260640
64,U000029,Paid Search,2025-02-08 01:33:03,0.000000,0.297862

In [44]:
# Time-Decay Attribution Summary

converted_touchpoints["time_decay_attributed_revenue"] = (
    converted_touchpoints["revenue"] *
    converted_touchpoints["time_decay_credit"]
)

time_decay_summary = (
    converted_touchpoints
    .groupby("channel")
    .agg(
        attributed_conversions=("time_decay_credit", "sum"),
        attributed_revenue=("time_decay_attributed_revenue", "sum")
    )
)

# Add channel spend
time_decay_summary = time_decay_summary.join(
    channel_summary["spend"]
)

# CAC
time_decay_summary["CAC"] = (
    time_decay_summary["spend"] /
    time_decay_summary["attributed_conversions"]
)

# ROAS
time_decay_summary["ROAS"] = (
    time_decay_summary["attributed_revenue"] /
    time_decay_summary["spend"]
)

time_decay_summary.round(2)

,attributed_conversions,attributed_revenue,spend,CAC,ROAS
channel,,,,,
Direct,631.95,1596352.70,0.00,0.00,inf
Display,344.74,133688.36,21173.13,61.42,6.31
Email,521.02,948861.67,0.00,0.00,inf
Organic Search,477.09,629274.12,0.00,0.00,inf
Paid Search,578.90,1184829.55,231677.45,400.21,5.11
Paid Social,536.72,196735.41,72535.83,135.15,2.71
Referral,423.59,447149.57,0.00,0.00,inf

In [46]:
# Position-Based Attribution

converted_users = touchpoints[
    touchpoints["converted"] == 1
].copy()

converted_users = converted_users.sort_values(
    ["user_id", "touch_order"]
)

def position_based_credit(group):
    n = len(group)

    if n == 1:
        credits = [1.0]

    elif n == 2:
        credits = [0.5, 0.5]

    else:
        middle_credit = 0.20 / (n - 2)
        credits = [0.40] + [middle_credit] * (n - 2) + [0.40]

    group = group.copy()
    group["position_based_credit"] = credits

    return group


position_based_touchpoints = (
    converted_users
    .groupby("user_id", group_keys=False)
    .apply(position_based_credit)
    .reset_index(drop=True)
)

position_based_touchpoints.head(10)

,touch_order,journey_length,channel,timestamp,cost,converted,revenue,position_based_credit
0,1,2,Paid Social,2025-03-20 00:00:00,5.78,1,0.00,0.5
1,2,2,Paid Search,2025-03-20 04:10:04,44.68,1,4544.66,0.5
2,1,2,Organic Search,2025-02-24 00:00:00,0.00,1,0.00,0.5
3,2,2,Referral,2025-02-24 11:05:24,0.00,1,1825.12,0.5
4,1,1,Email,2025-02-08 00:00:00,0.00,1,2586.91,1.0
5,1,1,Direct,2025-03-06 00:00:00,0.00,1,3864.37,1.0
6,1,4,Display,2025-02-05 00:00:00,3.80,1,0.00,0.4
7,2,4,Paid Social,2025-02-05 01:52:03,12.23,1,0.00,0.1
8,3,4,Paid Social,2025-02-06 17:11:49,14.35,1,0.00,0.1
9,4,4,Paid Search,2025-02-08 01:33:03,28.57,1,2609.12,0.4

In [47]:
# Position-Based Attribution Summary

position_based_touchpoints["position_based_attributed_revenue"] = (
    position_based_touchpoints["revenue"] *
    position_based_touchpoints["position_based_credit"]
)

position_based_summary = (
    position_based_touchpoints
    .groupby("channel")
    .agg(
        attributed_conversions=("position_based_credit", "sum"),
        attributed_revenue=("position_based_attributed_revenue", "sum")
    )
)

# Add channel spend
position_based_summary = position_based_summary.join(
    channel_summary["spend"]
)

# CAC
position_based_summary["CAC"] = (
    position_based_summary["spend"] /
    position_based_summary["attributed_conversions"]
)

# ROAS
position_based_summary["ROAS"] = (
    position_based_summary["attributed_revenue"] /
    position_based_summary["spend"]
)

position_based_summary.round(2)

,attributed_conversions,attributed_revenue,spend,CAC,ROAS
channel,,,,,
Direct,649.60,1780226.88,0.00,0.00,inf
Display,383.70,155879.25,21173.13,55.18,7.36
Email,450.30,1067258.56,0.00,0.00,inf
Organic Search,464.33,694107.08,0.00,0.00,inf
Paid Search,567.53,1312501.21,231677.45,408.22,5.67
Paid Social,591.00,221148.60,72535.83,122.73,3.05
Referral,407.53,509570.85,0.00,0.00,inf

In [48]:
# Compare attributed conversions across all models

attribution_comparison = pd.concat(
    {
        "First-Touch": first_touch_summary["attributed_conversions"],
        "Last-Touch": last_touch_summary["attributed_conversions"],
        "Linear": linear_summary["attributed_conversions"],
        "Time-Decay": time_decay_summary["attributed_conversions"],
        "Position-Based": position_based_summary["attributed_conversions"]
    },
    axis=1
)

attribution_comparison.round(2)

                First-Touch  Last-Touch  Linear  Time-Decay  Position-Based
channel
Direct                  298        1062  611.38      631.95          649.60
Display                 703          96  361.42      344.74          383.70
Email                   149         657  508.30      521.02          450.30
Organic Search          490         414  479.93      477.09          464.33
Paid Search             324         820  565.33      578.90          567.53
Paid Social            1095         133  561.87      536.72          591.00
Referral                455         332  425.77      423.59          407.53

In [49]:
# Validate total attributed conversions for each model

print("First-Touch:", first_touch_summary["attributed_conversions"].sum())
print("Last-Touch:", last_touch_summary["attributed_conversions"].sum())
print("Linear:", linear_summary["attributed_conversions"].sum())
print("Time-Decay:", time_decay_summary["attributed_conversions"].sum())
print("Position-Based:", position_based_summary["attributed_conversions"].sum())

First-Touch: 3514
Last-Touch: 3514
Linear: 3514.0
Time-Decay: 3514.0
Position-Based: 3514.0

In [51]:
# Inspect benchmark-related logic in the data generator

with open("data/raw/generate_attribution_data.py", "r", encoding="utf-8") as f:
    generator_code = f.read()

for line in generator_code.splitlines():
    if "ground_truth" in line.lower() or "benchmark" in line.lower():
        print(line)

In [52]:
# Create the controlled synthetic benchmark

touchpoints["role"] = np.where(
    touchpoints["journey_length"] == 1,
    "closer",
    np.where(
        touchpoints["touch_order"] == 1,
        "opener",
        np.where(
            touchpoints["touch_order"] == touchpoints["journey_length"],
            "closer",
            "middle"
        )
    )
)

CHANNEL_PROFILE = {
    "Paid Social":    {"opener": 0.90, "closer": 0.20, "middle": 0.40},
    "Display":        {"opener": 0.70, "closer": 0.15, "middle": 0.30},
    "Organic Search": {"opener": 0.50, "closer": 0.50, "middle": 0.40},
    "Referral":       {"opener": 0.50, "closer": 0.40, "middle": 0.40},
    "Paid Search":    {"opener": 0.30, "closer": 0.80, "middle": 0.40},
    "Email":          {"opener": 0.10, "closer": 0.70, "middle": 0.50},
    "Direct":         {"opener": 0.20, "closer": 0.90, "middle": 0.30},
}

# Assign the benchmark weight to each touchpoint
touchpoints["ground_truth_weight"] = touchpoints.apply(
    lambda row: CHANNEL_PROFILE[row["channel"]][row["role"]],
    axis=1
)

# Only converted journeys are evaluated
ground_truth_data = touchpoints[
    touchpoints["converted"] == 1
].copy()

# Normalize benchmark weights within each customer journey
ground_truth_data["ground_truth_credit"] = (
    ground_truth_data["ground_truth_weight"] /
    ground_truth_data.groupby("user_id")["ground_truth_weight"].transform("sum")
)

# Allocate revenue using benchmark credit
ground_truth_data["ground_truth_attributed_revenue"] = (
    ground_truth_data["revenue"] *
    ground_truth_data["ground_truth_credit"]
)

ground_truth_summary = (
    ground_truth_data
    .groupby("channel")
    .agg(
        attributed_conversions=("ground_truth_credit", "sum"),
        attributed_revenue=("ground_truth_attributed_revenue", "sum")
    )
)

ground_truth_summary.round(2)

                attributed_conversions  attributed_revenue
channel
Direct                          659.51          1882869.91
Display                         348.26            66222.59
Email                           511.59          1019204.49
Organic Search                  428.90           573202.37
Paid Search                     575.30          1339159.44
Paid Social                     626.83           112482.31
Referral                        363.61           368447.45

In [53]:
# Compare all attribution models against the controlled benchmark

model_comparison = pd.concat(
    {
        "First-Touch": first_touch_summary["attributed_conversions"],
        "Last-Touch": last_touch_summary["attributed_conversions"],
        "Linear": linear_summary["attributed_conversions"],
        "Time-Decay": time_decay_summary["attributed_conversions"],
        "Position-Based": position_based_summary["attributed_conversions"],
        "Ground Truth": ground_truth_summary["attributed_conversions"]
    },
    axis=1
)

model_comparison = model_comparison.round(2)

model_comparison

,First-Touch,Last-Touch,Linear,Time-Decay,Position-Based,Ground Truth
channel,,,,,,
Direct,298,1062,611.38,631.95,649.60,659.51
Display,703,96,361.42,344.74,383.70,348.26
Email,149,657,508.30,521.02,450.30,511.59
Organic Search,490,414,479.93,477.09,464.33,428.90
Paid Search,324,820,565.33,578.90,567.53,575.30
Paid Social,1095,133,561.87,536.72,591.00,626.83
Referral,455,332,425.77,423.59,407.53,363.61

In [54]:
# Calculate attribution error for each model

benchmark = model_comparison["Ground Truth"]

mae_results = {}

for model in [
    "First-Touch",
    "Last-Touch",
    "Linear",
    "Time-Decay",
    "Position-Based"
]:
    mae_results[model] = (
        model_comparison[model] - benchmark
    ).abs().mean()

mae_table = pd.DataFrame(
    mae_results.items(),
    columns=["Model", "MAE"]
).sort_values("MAE")

mae_table.round(2)

            Model     MAE
4  Position-Based   32.80
3      Time-Decay   34.63
2          Linear   36.10
1      Last-Touch  226.46
0     First-Touch  278.69

## Final Business Insights

### 1. Customer Journey Behavior
Longer customer journeys show higher conversion rates, indicating that customers with multiple marketing interactions are more likely to convert.

### 2. Attribution Model Impact
Attribution model choice significantly changes the amount of conversion credit assigned to each marketing channel.

### 3. Last-Touch Limitation
Last-Touch attribution heavily favors channels that appear near the end of the customer journey and can undervalue channels that contribute earlier in the journey.

### 4. Paid Channel Evaluation
The three paid channels — Paid Search, Paid Social, and Display — should be evaluated using multi-touch attribution rather than Last-Touch alone because their contribution changes substantially across models.

### 5. Benchmark Validation
Against the controlled synthetic benchmark, Position-Based Attribution achieved the lowest Mean Absolute Error (MAE), followed by Time-Decay and Linear Attribution.

### 6. Business Recommendation
For budget allocation decisions, management should not rely exclusively on Last-Touch attribution. A multi-touch approach, particularly Position-Based Attribution in this controlled analysis, provides a more balanced view of channel contribution.

### Important Limitation
The benchmark represents the known generative structure of this synthetic dataset. It is a validation benchmark, not real-world causal ground truth.

## Notebook Conclusion

This analysis evaluated customer journeys, channel performance, marketing spend, CAC, ROAS, and five attribution models.

The analysis demonstrates that attribution methodology can materially affect marketing channel evaluation and budget decisions.

The next stage of the project is to reproduce the cleaned analytical data in MySQL and perform SQL-based analysis before building the Excel budget allocation model and Power BI executive dashboard.